#!/usr/bin/env python3
"""
Generate Pine Script v6 from optimized parameters.

Reads the active Montauk 8.2 strategy and replaces input defaults
with the provided parameter overrides. Outputs a complete, ready-to-paste
Pine Script file.

Usage:
  python3 scripts/generate_pine.py '{"short_ema_len": 12, "atr_multiplier": 2.5}' "9.0-candidate-1"
  python3 scripts/generate_pine.py '{"short_ema_len": 12}' "9.0-candidate-1" --output remote/candidate.txt
"""

import json
import os
import re
import sys
from datetime import datetime

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STRATEGY_PATH = os.path.join(PROJECT_ROOT, "src", "strategy", "active", "Project Montauk 8.2.txt")

# Maps Python param names to Pine Script input variable names and their input.* type
PARAM_MAP = {
    "short_ema_len":         ("shortEmaLen",         "int"),
    "med_ema_len":           ("medEmaLen",           "int"),
    "long_ema_len":          ("longEmaLen",          "int"),
    "enable_trend":          ("enableTrend",         "bool"),
    "trend_ema_len":         ("trendEmaLen",         "int"),
    "slope_lookback":        ("slopeLookback",       "int"),
    "min_trend_slope":       ("minTrendSlope",       "float"),
    "enable_slope_filter":   ("enableSlopeFilter",   "bool"),
    "enable_below_filter":   ("enableBelowFilter",   "bool"),
    "triple_ema_len":        ("tripleEmaLen",        "int"),
    "triple_slope_lookback": ("tripleSlopeLookback", "int"),
    "enable_sideways_filter":("enableSidewaysFilter","bool"),
    "range_len":             ("rangeLen",            "int"),
    "max_range_pct":         ("maxRangePct",         "float"),
    "enable_sell_confirm":   ("enableSellConfirm",   "bool"),
    "sell_confirm_bars":     ("sellConfirmBars",     "int"),
    "sell_buffer_pct":       ("sellBufferPct",       "float"),
    "enable_sell_cooldown":  ("enableSellCooldown",  "bool"),
    "sell_cooldown_bars":    ("sellCooldownBars",    "int"),
    "enable_atr_exit":       ("enableATRExit",       "bool"),
    "atr_period":            ("atrPeriod",           "int"),
    "atr_multiplier":        ("atrMultiplier",       "float"),
    "enable_quick_exit":     ("enableQuickExit",     "bool"),
    "quick_ema_len":         ("quickEmaLen",         "int"),
    "quick_lookback_bars":   ("quickLookbackBars",   "int"),
    "quick_delta_pct_thresh":("quickDeltaPctThresh", "float"),
    "enable_trail_stop":     ("enableTrailStop",     "bool"),
    "trail_drop_pct":        ("trailDropPct",        "float"),
    "enable_tema_exit":      ("enableTemaExit",      "bool"),
    "tema_exit_lookback":    ("temaExitLookback",    "int"),
}


def format_value(val, pine_type: str) -> str:
    if pine_type == "bool":
        return "true" if val else "false"
    elif pine_type == "int":
        return str(int(val))
    elif pine_type == "float":
        if val == int(val):
            return f"{val:.1f}"
        return str(val)
    return str(val)


def generate(params: dict, version_name: str, output_path: str | None = None) -> str:
    with open(STRATEGY_PATH) as f:
        pine = f.read()

    # Replace strategy name
    pine = pine.replace(
        'strategy("Project Montauk 8.2"',
        f'strategy("Project Montauk {version_name}"'
    )
    pine = pine.replace(
        'shorttitle="Montauk 8.2"',
        f'shorttitle="Montauk {version_name}"'
    )

    # Replace each parameter's default value in the input.* call
    changes = []
    for py_name, value in params.items():
        if py_name not in PARAM_MAP:
            continue

        pine_var, pine_type = PARAM_MAP[py_name]
        new_val_str = format_value(value, pine_type)

        if pine_type == "bool":
            pattern = rf'({pine_var}\s*=\s*input\.bool\()(\w+)(\s*,)'
        elif pine_type == "int":
            pattern = rf'({pine_var}\s*=\s*input\.int\()(-?\d+)(\s*,)'
        elif pine_type == "float":
            pattern = rf'({pine_var}\s*=\s*input\.float\()(-?[\d.]+)(\s*,)'
        else:
            continue

        match = re.search(pattern, pine)
        if match:
            old_val = match.group(2)
            pine = re.sub(pattern, rf'\g<1>{new_val_str}\3', pine, count=1)
            changes.append(f"  {pine_var}: {old_val} -> {new_val_str}")

    # Add comment header
    header = (
        f"// Generated by /spike optimization on {datetime.now().strftime('%Y-%m-%d')}\n"
        f"// Base: Montauk 8.2 | Version: {version_name}\n"
        f"// Parameter changes:\n"
    )
    for c in changes:
        header += f"// {c}\n"
    header += "//\n"

    pine = header + pine

    if output_path:
        os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)
        with open(output_path, "w") as f:
            f.write(pine)
        print(f"Written to: {output_path}")

    print(f"Generated Montauk {version_name}")
    print(f"Changes ({len(changes)}):")
    for c in changes:
        print(c)

    return pine


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_pine.py '<json params>' '<version name>' [--output <path>]")
        sys.exit(1)

    params = json.loads(sys.argv[1])
    version_name = sys.argv[2]

    output_path = None
    if "--output" in sys.argv:
        idx = sys.argv.index("--output")
        output_path = sys.argv[idx + 1]
    else:
        date_str = datetime.now().strftime("%Y-%m-%d")
        output_path = os.path.join(PROJECT_ROOT, "remote", f"candidate-{date_str}-{version_name}.txt")

    generate(params, version_name, output_path)


if __name__ == "__main__":
    main()
