#!/usr/bin/env python3
"""
Generate Pine Script v6 code from a parameter configuration.

Takes a JSON params dict and produces a full Montauk strategy script
that can be pasted directly into TradingView.
"""

import json
import sys
import os
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from backtest_engine import StrategyParams


def generate_pine(params: StrategyParams, version: str = "9.0-candidate") -> str:
    """Generate full Pine Script v6 strategy from params."""
    p = params

    script = f'''//@version=6
strategy("Project Montauk {version}",
     overlay=true,
     shorttitle="Montauk {version}",
     initial_capital=1000,
     default_qty_type=strategy.percent_of_equity,
     default_qty_value=100,
     pyramiding=0,
     commission_type=strategy.commission.percent,
     commission_value=0,
     slippage=0,
     calc_on_every_tick=false,
     process_orders_on_close=true)

// Generated by Montauk Optimizer on {datetime.now().strftime("%Y-%m-%d %H:%M")}
// Do not edit directly — re-run optimizer to generate new versions.

// ─────────────────────────────────────────────────────────────────────────────
// Group 1 — EMAs
// ─────────────────────────────────────────────────────────────────────────────
shortEmaLen         = input.int({p.short_ema_len},   title="Short EMA Length",                        minval=1, group="1 - EMAs")
medEmaLen           = input.int({p.med_ema_len},   title="Medium EMA Length",                       minval=1, group="1 - EMAs")
longEmaLen          = input.int({p.long_ema_len},  title="Long EMA Length",                         minval=1, group="1 - EMAs")

// ─────────────────────────────────────────────────────────────────────────────
// Group 2 — Trend Filter
// ─────────────────────────────────────────────────────────────────────────────
enableTrend         = input.bool({str(p.enable_trend).lower()},  title="Enable Trend Filter",                              group="2 - Trend Filter")
trendEmaLen         = input.int({p.trend_ema_len},     title="Trend EMA Length",          minval=1,              group="2 - Trend Filter")
slopeLookback       = input.int({p.slope_lookback},     title="Slope Lookback Bars",        minval=1,             group="2 - Trend Filter")
minTrendSlope       = input.float({p.min_trend_slope},  title="Min Trend EMA Slope",        step=0.0001,          group="2 - Trend Filter")

// ─────────────────────────────────────────────────────────────────────────────
// Group 3 — TEMA Filters  (entry gates only)
// ─────────────────────────────────────────────────────────────────────────────
enableSlopeFilter   = input.bool({str(p.enable_slope_filter).lower()}, title="Enable No-Buy When TEMA Slope Negative",           group="3 - TEMA Filters")
enableBelowFilter   = input.bool({str(p.enable_below_filter).lower()}, title="Enable No-Buy When Price Below TEMA",              group="3 - TEMA Filters")
tripleEmaLen        = input.int({p.triple_ema_len},    title="Triple EMA Length",          minval=1,             group="3 - TEMA Filters")
tripleSlopeLookback = input.int({p.triple_slope_lookback},      title="TEMA Entry Slope Lookback",  minval=1,             group="3 - TEMA Filters")

// ─────────────────────────────────────────────────────────────────────────────
// Group 4 — Sideways Filter
// ─────────────────────────────────────────────────────────────────────────────
enableSidewaysFilter = input.bool({str(p.enable_sideways_filter).lower()}, title="Enable Sideways Market Filter",                    group="4 - Sideways Filter")
rangeLen             = input.int({p.range_len},    title="Range Lookback Bars",        minval=1,             group="4 - Sideways Filter")
maxRangePct          = input.float({p.max_range_pct},title="Max Range (%)",              step=0.1,             group="4 - Sideways Filter")

// ─────────────────────────────────────────────────────────────────────────────
// Group 5 — Sell Confirmation
// ─────────────────────────────────────────────────────────────────────────────
enableSellConfirm   = input.bool({str(p.enable_sell_confirm).lower()},  title="Enable Sell Confirmation",                         group="5 - Sell Confirmation")
sellConfirmBars     = input.int({p.sell_confirm_bars},      title="Sell Confirm Bars",          minval=1,             group="5 - Sell Confirmation")
sellBufferPct       = input.float({p.sell_buffer_pct},  title="Sell Buffer (%)",            step=0.01,            group="5 - Sell Confirmation")

// ─────────────────────────────────────────────────────────────────────────────
// Group 6 — Sell Cooldown
// ─────────────────────────────────────────────────────────────────────────────
enableSellCooldown  = input.bool({str(p.enable_sell_cooldown).lower()},  title="Enable Sell Cooldown",                             group="6 - Sell Cooldown")
sellCooldownBars    = input.int({p.sell_cooldown_bars},      title="Sell Cooldown (bars)",       minval=0,             group="6 - Sell Cooldown")

// ─────────────────────────────────────────────────────────────────────────────
// Group 7 — ATR Exit
// ─────────────────────────────────────────────────────────────────────────────
enableATRExit       = input.bool({str(p.enable_atr_exit).lower()},  title="Enable ATR Exit",                                  group="7 - ATR Exit")
atrPeriod           = input.int({p.atr_period},     title="ATR Period",                 minval=1,             group="7 - ATR Exit")
atrMultiplier       = input.float({p.atr_multiplier},  title="ATR Multiplier",             step=0.1,             group="7 - ATR Exit")

// ─────────────────────────────────────────────────────────────────────────────
// Group 8 — Quick EMA Exit
// ─────────────────────────────────────────────────────────────────────────────
enableQuickExit     = input.bool({str(p.enable_quick_exit).lower()},  title="Enable Quick EMA Exit",                            group="8 - Quick EMA Exit")
quickEmaLen         = input.int({p.quick_ema_len},     title="Quick EMA Length",           minval=1,             group="8 - Quick EMA Exit")
quickLookbackBars   = input.int({p.quick_lookback_bars},      title="Quick Exit Lookback Bars",   minval=1,             group="8 - Quick EMA Exit")
quickDeltaPctThresh = input.float({p.quick_delta_pct_thresh}, title="Quick EMA Δ% Threshold (%)", step=0.1,            group="8 - Quick EMA Exit")

// ─────────────────────────────────────────────────────────────────────────────
// Group 10 — Trailing Peak Stop
// ─────────────────────────────────────────────────────────────────────────────
enableTrailStop     = input.bool({str(p.enable_trail_stop).lower()}, title="Enable Trailing Peak Stop",                        group="10 - Trailing Peak Stop")
trailDropPct        = input.float({p.trail_drop_pct}, title="Max Drop From Peak (%)",     step=0.5, minval=1.0, group="10 - Trailing Peak Stop")

// ─────────────────────────────────────────────────────────────────────────────
// Group 11 — TEMA Slope Exit
// ─────────────────────────────────────────────────────────────────────────────
enableTemaExit      = input.bool({str(p.enable_tema_exit).lower()}, title="Enable TEMA Slope Exit",                           group="11 - TEMA Slope Exit")
temaExitLookback    = input.int({p.tema_exit_lookback},      title="TEMA Exit Slope Lookback",   minval=1,             group="11 - TEMA Slope Exit")

// ─────────────────────────────────────────────────────────────────────────────
// EMA Calculations
// ─────────────────────────────────────────────────────────────────────────────
emaShort  = ta.ema(close, shortEmaLen)
emaMed    = ta.ema(close, medEmaLen)
emaLong   = ta.ema(close, longEmaLen)
emaTrend  = ta.ema(close, trendEmaLen)
quickEma  = ta.ema(close, quickEmaLen)

// ─────────────────────────────────────────────────────────────────────────────
// Trend Filter
// ─────────────────────────────────────────────────────────────────────────────
trendSlope = (emaTrend - emaTrend[slopeLookback]) / slopeLookback
trendOk    = not enableTrend or (trendSlope > minTrendSlope)

// ─────────────────────────────────────────────────────────────────────────────
// TEMA (Triple EMA)
// ─────────────────────────────────────────────────────────────────────────────
ema1 = ta.ema(close, tripleEmaLen)
ema2 = ta.ema(ema1,  tripleEmaLen)
ema3 = ta.ema(ema2,  tripleEmaLen)
tema = 3 * ema1 - 3 * ema2 + ema3

// ─────────────────────────────────────────────────────────────────────────────
// TEMA Entry Filters
// ─────────────────────────────────────────────────────────────────────────────
temaSlope = (tema - tema[tripleSlopeLookback]) / tripleSlopeLookback
slopeOk   = not enableSlopeFilter or (temaSlope > 0)
aboveOk   = not enableBelowFilter or (close > tema)

// ─────────────────────────────────────────────────────────────────────────────
// Sideways Filter (Donchian range)
// ─────────────────────────────────────────────────────────────────────────────
rng        = ta.highest(high, rangeLen) - ta.lowest(low, rangeLen)
rngPct     = rng / ta.sma(close, rangeLen) * 100
sideways   = rngPct < maxRangePct
sidewaysOk = not enableSidewaysFilter or not sideways

// ─────────────────────────────────────────────────────────────────────────────
// Entry Conditions
// ─────────────────────────────────────────────────────────────────────────────
buyZone = emaShort > emaMed
buyOk   = buyZone and trendOk and slopeOk and aboveOk and sidewaysOk

// ─────────────────────────────────────────────────────────────────────────────
// Exit 1 — EMA Cross
// ─────────────────────────────────────────────────────────────────────────────
bufferOk    = emaShort < emaLong * (1 - sellBufferPct / 100)
allBelow    = true
if enableSellConfirm
    for j = 0 to sellConfirmBars - 1
        if not (emaShort[j] < emaLong[j])
            allBelow := false
confirmSell = not enableSellConfirm or allBelow
isCrossExit = bufferOk and confirmSell

// ─────────────────────────────────────────────────────────────────────────────
// Exit 2 — ATR Shock
// ─────────────────────────────────────────────────────────────────────────────
atr       = ta.atr(atrPeriod)
isAtrExit = enableATRExit and close < close[1] - atr * atrMultiplier

// ─────────────────────────────────────────────────────────────────────────────
// Exit 3 — Quick EMA
// ─────────────────────────────────────────────────────────────────────────────
quickEmaPast  = quickEma[quickLookbackBars]
quickDeltaPct = quickEmaPast != 0 ? 100.0 * (quickEma - quickEmaPast) / quickEmaPast : 0.0
isQuickExit   = enableQuickExit and quickDeltaPct <= quickDeltaPctThresh

// ─────────────────────────────────────────────────────────────────────────────
// Exit 4 — Trailing Peak Stop
// ─────────────────────────────────────────────────────────────────────────────
var float peakSinceEntry = na
if strategy.position_size > 0
    peakSinceEntry := na(peakSinceEntry) ? close : math.max(peakSinceEntry, close)
else
    peakSinceEntry := na

isTrailExit = enableTrailStop and strategy.position_size > 0 and
     not na(peakSinceEntry) and close < peakSinceEntry * (1 - trailDropPct / 100)

// ─────────────────────────────────────────────────────────────────────────────
// Exit 5 — TEMA Slope Exit
// ─────────────────────────────────────────────────────────────────────────────
temaExitSlope = (tema - tema[temaExitLookback]) / temaExitLookback
isTemaExit    = enableTemaExit and strategy.position_size > 0 and temaExitSlope < 0

// ─────────────────────────────────────────────────────────────────────────────
// Cooldown Tracking
// ─────────────────────────────────────────────────────────────────────────────
var int lastSellBar = na

// ─────────────────────────────────────────────────────────────────────────────
// Exit Reason
// ─────────────────────────────────────────────────────────────────────────────
var string exitReason = na
if strategy.position_size > 0
    if isCrossExit
        exitReason := "EMA Cross"
    else if isAtrExit
        exitReason := "ATR Exit"
    else if isQuickExit
        exitReason := "Quick EMA"
    else if isTrailExit
        exitReason := "Trail Stop"
    else if isTemaExit
        exitReason := "TEMA Slope"

// ─────────────────────────────────────────────────────────────────────────────
// Unified Exit
// ─────────────────────────────────────────────────────────────────────────────
allowExit = not (enableSidewaysFilter and sideways)
exitCond  = strategy.position_size > 0 and allowExit and
     (isCrossExit or isAtrExit or isQuickExit or isTrailExit or isTemaExit)

if exitCond
    strategy.close("Long")
    lastSellBar := bar_index
    label.new(bar_index, high, exitReason,
              yloc=yloc.abovebar,
              style=label.style_label_down,
              color=color.red, textcolor=color.white, size=size.tiny)

// ─────────────────────────────────────────────────────────────────────────────
// Entry with Cooldown
// ─────────────────────────────────────────────────────────────────────────────
canEnter = strategy.position_size == 0 and
     (not enableSellCooldown or na(lastSellBar) or (bar_index - lastSellBar) > sellCooldownBars)
if buyOk and canEnter
    strategy.entry("Long", strategy.long)

// ─────────────────────────────────────────────────────────────────────────────
// Plots
// ─────────────────────────────────────────────────────────────────────────────
plot(emaShort, title="Short EMA",  color=color.new(color.orange, 0))
plot(emaMed,   title="Medium EMA", color=color.new(color.teal,   0))
plot(emaLong,  title="Long EMA",   color=color.new(color.purple, 0))
plot(emaTrend, title="Trend EMA",  color=color.new(color.white,  80))
plot(quickEma, title="Quick EMA",  color=color.new(#ff0000,      60))
plot(tema,     title="Triple EMA", color=color.new(color.yellow, 0))

trailStopLevel = enableTrailStop and strategy.position_size > 0 and not na(peakSinceEntry)
     ? peakSinceEntry * (1 - trailDropPct / 100)
     : na
plot(trailStopLevel, title="Trail Stop Level",
     color=color.new(color.red, 20), style=plot.style_linebr, linewidth=1)
'''
    return script


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python generate_pine.py '<json_params>' [version_name]")
        print("Example: python generate_pine.py '{\"short_ema_len\": 12}' 9.0-alpha")
        sys.exit(1)

    overrides = json.loads(sys.argv[1])
    version = sys.argv[2] if len(sys.argv) > 2 else "9.0-candidate"

    base = StrategyParams().to_dict()
    base.update(overrides)
    params = StrategyParams.from_dict(base)

    pine = generate_pine(params, version)
    print(pine)
