#!/usr/bin/env python3
"""
Generate Pine Script candidate files for validated spike winners.

The generator is explicit per strategy family. That is deliberate: the
optimizer can select materially different logic families, so emitting a
"best effort" approximation would be misleading.
"""

from __future__ import annotations

import os
from pathlib import Path
from textwrap import dedent

from deploy import ACTIVE_PINE_PATH, patch_pine_script


PROJECT_ROOT = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def _pine_number(value, *, force_float: bool = False) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int) and not force_float:
        return str(value)
    text = f"{float(value):.6f}".rstrip("0").rstrip(".")
    if "." not in text:
        text += ".0"
    return text


def _header(title: str, shorttitle: str, strategy_name: str) -> str:
    return dedent(
        f"""\
        //@version=6
        strategy("{title}",
             overlay=true,
             shorttitle="{shorttitle}",
             initial_capital=1000,
             default_qty_type=strategy.percent_of_equity,
             default_qty_value=100,
             pyramiding=0,
             commission_type=strategy.commission.percent,
             commission_value=0.05,
             slippage=0,
             calc_on_every_tick=false,
             process_orders_on_close=true)

        // Generated by scripts/pine_generator.py
        // Source strategy family: {strategy_name}

        """
    )


def _wrap(title: str, shorttitle: str, strategy_name: str, body: str) -> str:
    footer = dedent(
        """

        riskState = strategy.position_size > 0 ? 1 : 0
        riskOn = riskState == 1
        riskOff = riskState == 0
        riskOnFlip = ta.change(riskState) > 0
        riskOffFlip = ta.change(riskState) < 0

        plot(riskState, "Risk State", color=color.new(color.gray, 100), display=display.data_window)
        alertcondition(riskOnFlip, "Risk On", "Project Montauk risk_state=risk_on")
        alertcondition(riskOffFlip, "Risk Off", "Project Montauk risk_state=risk_off")
        """
    ).strip()
    return _header(title, shorttitle, strategy_name) + dedent(body).strip() + "\n\n" + footer + "\n"


def _build_montauk_821(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Montauk 8.2.1 Logic",
        "Montauk Cand",
        "montauk_821",
        f"""
        shortEmaLen         = input.int({_pine_number(params.get("short_ema", 15))}, "Short EMA Length", minval=1, group="1 - Inputs")
        medEmaLen           = input.int({_pine_number(params.get("med_ema", 30))}, "Medium EMA Length", minval=1, group="1 - Inputs")
        trendEmaLen         = input.int({_pine_number(params.get("trend_ema", 70))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        slopeLookback       = input.int({_pine_number(params.get("slope_lookback", 10))}, "Trend Slope Lookback", minval=1, group="1 - Inputs")
        atrPeriod           = input.int({_pine_number(params.get("atr_period", 40))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier       = input.float({_pine_number(params.get("atr_mult", 3.0), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        quickEmaLen         = input.int({_pine_number(params.get("quick_ema", 15))}, "Quick EMA Length", minval=1, group="1 - Inputs")
        quickLookbackBars   = input.int({_pine_number(params.get("quick_lookback", 5))}, "Quick EMA Lookback", minval=1, group="1 - Inputs")
        quickDeltaPctThresh = input.float({_pine_number(params.get("quick_thresh", -8.2), force_float=True)}, "Quick EMA Delta Threshold", step=0.1, group="1 - Inputs")
        sellBufferPct       = input.float({_pine_number(params.get("sell_buffer", 0.2), force_float=True)}, "Sell Buffer Pct", step=0.01, group="1 - Inputs")
        cooldownBars        = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        emaShort = ta.ema(close, shortEmaLen)
        emaMed   = ta.ema(close, medEmaLen)
        emaTrend = ta.ema(close, trendEmaLen)
        quickEma = ta.ema(close, quickEmaLen)
        atrVal   = ta.atr(atrPeriod)

        trendSlope = (emaTrend - emaTrend[slopeLookback]) / slopeLookback
        trendOk    = na(emaTrend) or na(emaTrend[slopeLookback]) or trendSlope > 0
        entrySignal = emaShort > emaMed and trendOk

        quickEmaPast  = quickEma[quickLookbackBars]
        quickDeltaPct = quickEmaPast != 0 ? 100.0 * (quickEma - quickEmaPast) / quickEmaPast : 0.0

        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        isQuickExit = strategy.position_size > 0 and quickDeltaPct <= quickDeltaPctThresh
        isCrossExit = strategy.position_size > 0 and emaShort < emaMed * (1 - sellBufferPct / 100)

        exitCond = isAtrExit or isQuickExit or isCrossExit
        var string exitReason = na
        if strategy.position_size > 0
            if isAtrExit
                exitReason := "ATR Shock"
            else if isQuickExit
                exitReason := "Quick EMA"
            else if isCrossExit
                exitReason := "EMA Cross"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(emaShort, "EMA Short", color=color.new(color.teal, 0))
        plot(emaMed, "EMA Med", color=color.new(color.orange, 0))
        plot(emaTrend, "EMA Trend", color=color.new(color.blue, 30))
        """,
    )


def _build_rsi_regime(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - RSI Regime",
        "RSI Regime",
        "rsi_regime",
        f"""
        rsiLen       = input.int({_pine_number(params.get("rsi_len", 14))}, "RSI Length", minval=1, group="1 - Inputs")
        entryRsi     = input.float({_pine_number(params.get("entry_rsi", 35.0), force_float=True)}, "Entry RSI", step=1.0, group="1 - Inputs")
        exitRsi      = input.float({_pine_number(params.get("exit_rsi", 75.0), force_float=True)}, "Exit RSI", step=1.0, group="1 - Inputs")
        panicRsi     = input.float({_pine_number(params.get("panic_rsi", 20.0), force_float=True)}, "Panic RSI", step=1.0, group="1 - Inputs")
        trendLen     = input.int({_pine_number(params.get("trend_len", 100))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        rsiVal   = ta.rsi(close, rsiLen)
        trendEma = ta.ema(close, trendLen)

        entrySignal = ta.crossover(rsiVal, entryRsi) and (na(trendEma) or close > trendEma)
        isOverboughtExit = strategy.position_size > 0 and rsiVal >= exitRsi
        isPanicExit      = strategy.position_size > 0 and rsiVal < panicRsi
        exitCond         = isOverboughtExit or isPanicExit

        var string exitReason = na
        if strategy.position_size > 0
            if isOverboughtExit
                exitReason := "RSI Overbought"
            else if isPanicExit
                exitReason := "RSI Panic"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.orange, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(trendEma, "Trend EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_breakout(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Breakout",
        "Breakout",
        "breakout",
        f"""
        lookback      = input.int({_pine_number(params.get("lookback", 60))}, "Breakout Lookback", minval=1, group="1 - Inputs")
        breakoutPct   = input.float({_pine_number(params.get("breakout_pct", 0.98), force_float=True)}, "Breakout Percent Of High", step=0.01, group="1 - Inputs")
        trailPct      = input.float({_pine_number(params.get("trail_pct", 20.0), force_float=True)}, "Trailing Stop Pct", step=0.5, group="1 - Inputs")
        atrPeriod     = input.int({_pine_number(params.get("atr_period", 20))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier = input.float({_pine_number(params.get("atr_mult", 3.0), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        cooldownBars  = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        breakoutHigh = ta.highest(high, lookback)
        atrVal       = ta.atr(atrPeriod)
        entrySignal  = close >= breakoutHigh * breakoutPct

        var float peakSinceEntry = na
        if strategy.position_size > 0
            peakSinceEntry := na(peakSinceEntry) ? close : math.max(peakSinceEntry, close)
        else
            peakSinceEntry := na

        isTrailExit = strategy.position_size > 0 and not na(peakSinceEntry) and close < peakSinceEntry * (1 - trailPct / 100)
        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        exitCond    = isTrailExit or isAtrExit

        var string exitReason = na
        if strategy.position_size > 0
            if isTrailExit
                exitReason := "Trail Stop"
            else if isAtrExit
                exitReason := "ATR Shock"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(breakoutHigh, "Breakout High", color=color.new(color.green, 50))
        """,
    )


def _build_rsi_vol_regime(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - RSI Vol Regime",
        "RSI Vol",
        "rsi_vol_regime",
        f"""
        rsiLen       = input.int({_pine_number(params.get("rsi_len", 13))}, "RSI Length", minval=1, group="1 - Inputs")
        trendLen     = input.int({_pine_number(params.get("trend_len", 150))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        entryRsi     = input.float({_pine_number(params.get("entry_rsi", 35.0), force_float=True)}, "Entry RSI", step=1.0, group="1 - Inputs")
        exitRsi      = input.float({_pine_number(params.get("exit_rsi", 80.0), force_float=True)}, "Exit RSI", step=1.0, group="1 - Inputs")
        panicRsi     = input.float({_pine_number(params.get("panic_rsi", 15.0), force_float=True)}, "Panic RSI", step=1.0, group="1 - Inputs")
        volShortLen  = input.int({_pine_number(params.get("vol_short", 15))}, "Vol Short Length", minval=2, group="1 - Inputs")
        volLongLen   = input.int({_pine_number(params.get("vol_long", 60))}, "Vol Long Length", minval=2, group="1 - Inputs")
        volRatioMax  = input.float({_pine_number(params.get("vol_ratio_max", 0.95), force_float=True)}, "Entry Vol Ratio Max", step=0.05, group="1 - Inputs")
        volExitRatio = input.float({_pine_number(params.get("vol_exit_ratio", 1.5), force_float=True)}, "Exit Vol Ratio", step=0.05, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        rsiVal      = ta.rsi(close, rsiLen)
        trendEma    = ta.ema(close, trendLen)
        dailyReturn = close[1] != 0 ? (close - close[1]) / close[1] : 0.0
        volShort    = ta.stdev(dailyReturn, volShortLen)
        volLong     = ta.stdev(dailyReturn, volLongLen)
        volRatio    = volLong > 0 ? volShort / volLong : 1.0

        trendOk    = na(trendEma) or close > trendEma
        volEntryOk = volRatio < volRatioMax
        entrySignal = ta.crossover(rsiVal, entryRsi) and trendOk and volEntryOk

        isRsiOverbought = strategy.position_size > 0 and rsiVal >= exitRsi
        isRsiPanic      = strategy.position_size > 0 and rsiVal < panicRsi
        isVolSpike      = strategy.position_size > 0 and volRatio > volExitRatio
        exitCond        = isRsiOverbought or isRsiPanic or isVolSpike

        var string exitReason = na
        if strategy.position_size > 0
            if isRsiOverbought
                exitReason := "RSI Overbought"
            else if isRsiPanic
                exitReason := "RSI Panic"
            else if isVolSpike
                exitReason := "Vol Spike"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(trendEma, "Trend EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_rsi_regime_trail(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - RSI Regime Trail",
        "RSI Trail",
        "rsi_regime_trail",
        f"""
        rsiLen       = input.int({_pine_number(params.get("rsi_len", 14))}, "RSI Length", minval=1, group="1 - Inputs")
        trendLen     = input.int({_pine_number(params.get("trend_len", 150))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        entryRsi     = input.float({_pine_number(params.get("entry_rsi", 35.0), force_float=True)}, "Entry RSI", step=1.0, group="1 - Inputs")
        trailPct     = input.float({_pine_number(params.get("trail_pct", 25.0), force_float=True)}, "Trail Stop Pct", step=0.5, group="1 - Inputs")
        panicRsi     = input.float({_pine_number(params.get("panic_rsi", 15.0), force_float=True)}, "Panic RSI", step=1.0, group="1 - Inputs")
        atrPeriod    = input.int({_pine_number(params.get("atr_period", 30))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier= input.float({_pine_number(params.get("atr_mult", 3.5), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        rsiVal   = ta.rsi(close, rsiLen)
        trendEma = ta.ema(close, trendLen)
        atrVal   = ta.atr(atrPeriod)

        entrySignal = ta.crossover(rsiVal, entryRsi) and (na(trendEma) or close > trendEma)

        var float peakSinceEntry = na
        if strategy.position_size > 0
            peakSinceEntry := na(peakSinceEntry) ? close : math.max(peakSinceEntry, close)
        else
            peakSinceEntry := na

        isTrailExit = strategy.position_size > 0 and not na(peakSinceEntry) and close < peakSinceEntry * (1 - trailPct / 100)
        isPanicExit = strategy.position_size > 0 and rsiVal < panicRsi
        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        exitCond    = isTrailExit or isPanicExit or isAtrExit

        var string exitReason = na
        if strategy.position_size > 0
            if isTrailExit
                exitReason := "Trail Stop"
            else if isPanicExit
                exitReason := "RSI Panic"
            else if isAtrExit
                exitReason := "ATR Shock"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(trendEma, "Trend EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_vol_regime(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Volatility Regime",
        "Vol Regime",
        "vol_regime",
        f"""
        volShortLen   = input.int({_pine_number(params.get("vol_short", 20))}, "Vol Short Length", minval=2, group="1 - Inputs")
        volLongLen    = input.int({_pine_number(params.get("vol_long", 60))}, "Vol Long Length", minval=2, group="1 - Inputs")
        trendLen      = input.int({_pine_number(params.get("trend_len", 100))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        volEntryRatio = input.float({_pine_number(params.get("vol_entry_ratio", 0.9), force_float=True)}, "Vol Entry Ratio", step=0.05, group="1 - Inputs")
        volExitRatio  = input.float({_pine_number(params.get("vol_exit_ratio", 1.5), force_float=True)}, "Vol Exit Ratio", step=0.05, group="1 - Inputs")
        trendBuffer   = input.float({_pine_number(params.get("trend_buffer", 2.0), force_float=True)}, "Trend Buffer Pct", step=0.1, group="1 - Inputs")
        cooldownBars  = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        dailyReturn = close[1] != 0 ? (close - close[1]) / close[1] : 0.0
        volShort    = ta.stdev(dailyReturn, volShortLen)
        volLong     = ta.stdev(dailyReturn, volLongLen)
        trendEma    = ta.ema(close, trendLen)

        ratio     = volLong > 0 ? volShort / volLong : na
        prevRatio = volLong[1] > 0 ? volShort[1] / volLong[1] : na
        trendOk   = na(trendEma) or close > trendEma

        entrySignal = not na(prevRatio) and prevRatio >= volEntryRatio and ratio < volEntryRatio and trendOk
        isVolExit   = strategy.position_size > 0 and ratio > volExitRatio
        isTrendExit = strategy.position_size > 0 and not na(trendEma) and close < trendEma * (1 - trendBuffer / 100)
        exitCond    = isVolExit or isTrendExit

        var string exitReason = na
        if strategy.position_size > 0
            if isVolExit
                exitReason := "Vol Spike"
            else if isTrendExit
                exitReason := "Below Trend"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(trendEma, "Trend EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_ichimoku_trend(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Ichimoku Trend",
        "Ichimoku",
        "ichimoku_trend",
        f"""
        tenkanLen    = input.int({_pine_number(params.get("tenkan_len", 9))}, "Tenkan Length", minval=1, group="1 - Inputs")
        kijunLen     = input.int({_pine_number(params.get("kijun_len", 26))}, "Kijun Length", minval=1, group="1 - Inputs")
        cloudLen     = input.int({_pine_number(params.get("cloud_len", 52))}, "Cloud EMA Length", minval=1, group="1 - Inputs")
        cloudBuffer  = input.float({_pine_number(params.get("cloud_buffer", 1.0), force_float=True)}, "Cloud Buffer Pct", step=0.1, group="1 - Inputs")
        atrPeriod    = input.int({_pine_number(params.get("atr_period", 30))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier= input.float({_pine_number(params.get("atr_mult", 3.5), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        tenkan   = (ta.highest(high, tenkanLen) + ta.lowest(low, tenkanLen)) / 2
        kijun    = (ta.highest(high, kijunLen) + ta.lowest(low, kijunLen)) / 2
        cloudEma = ta.ema(close, cloudLen)
        atrVal   = ta.atr(atrPeriod)

        aboveCloud = na(cloudEma) or close > cloudEma
        entrySignal = ta.crossover(tenkan, kijun) and aboveCloud

        isTkExit    = strategy.position_size > 0 and ta.crossunder(tenkan, kijun)
        isCloudExit = strategy.position_size > 0 and not na(cloudEma) and close < cloudEma * (1 - cloudBuffer / 100)
        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        exitCond    = isTkExit or isCloudExit or isAtrExit

        var string exitReason = na
        if strategy.position_size > 0
            if isTkExit
                exitReason := "TK Cross Down"
            else if isCloudExit
                exitReason := "Below Cloud"
            else if isAtrExit
                exitReason := "ATR Shock"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(cloudEma, "Cloud EMA", color=color.new(color.blue, 50))
        plot(tenkan, "Tenkan", color=color.new(color.orange, 0))
        plot(kijun, "Kijun", color=color.new(color.teal, 0))
        """,
    )


def _build_dual_momentum(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Dual Momentum",
        "Dual Mom",
        "dual_momentum",
        f"""
        absPeriod     = input.int({_pine_number(params.get("abs_period", 60))}, "Absolute ROC Period", minval=1, group="1 - Inputs")
        shortPeriod   = input.int({_pine_number(params.get("short_period", 20))}, "Short ROC Period", minval=1, group="1 - Inputs")
        trendLen      = input.int({_pine_number(params.get("trend_len", 100))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        absThresh     = input.float({_pine_number(params.get("abs_thresh", 5.0), force_float=True)}, "Absolute ROC Threshold", step=0.1, group="1 - Inputs")
        shortThresh   = input.float({_pine_number(params.get("short_thresh", 2.0), force_float=True)}, "Short ROC Threshold", step=0.1, group="1 - Inputs")
        absExit       = input.float({_pine_number(params.get("abs_exit", -5.0), force_float=True)}, "Absolute Exit ROC", step=0.1, group="1 - Inputs")
        shortExit     = input.float({_pine_number(params.get("short_exit", -8.0), force_float=True)}, "Short Exit ROC", step=0.1, group="1 - Inputs")
        atrPeriod     = input.int({_pine_number(params.get("atr_period", 30))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier = input.float({_pine_number(params.get("atr_mult", 3.5), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        cooldownBars  = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        rocAbs    = ta.roc(close, absPeriod)
        rocShort  = ta.roc(close, shortPeriod)
        trendEma  = ta.ema(close, trendLen)
        atrVal    = ta.atr(atrPeriod)

        absOk       = rocAbs > absThresh
        shortOk     = rocShort > shortThresh
        prevNotBoth = rocAbs[1] <= absThresh or rocShort[1] <= shortThresh
        trendOk     = na(trendEma) or close > trendEma
        entrySignal = absOk and shortOk and prevNotBoth and trendOk

        isAbsExit   = strategy.position_size > 0 and rocAbs < absExit
        isShortExit = strategy.position_size > 0 and rocShort < shortExit
        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        exitCond    = isAbsExit or isShortExit or isAtrExit

        var string exitReason = na
        if strategy.position_size > 0
            if isAbsExit
                exitReason := "Abs Mom Exit"
            else if isShortExit
                exitReason := "Short Mom Exit"
            else if isAtrExit
                exitReason := "ATR Shock"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(trendEma, "Trend EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_always_in_trend(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Always In Trend",
        "Always In",
        "always_in_trend",
        f"""
        fastEmaLen   = input.int({_pine_number(params.get("fast_ema", 20))}, "Fast EMA Length", minval=1, group="1 - Inputs")
        slowEmaLen   = input.int({_pine_number(params.get("slow_ema", 50))}, "Slow EMA Length", minval=1, group="1 - Inputs")
        adxLen       = input.int({_pine_number(params.get("adx_len", 14))}, "ADX Length", minval=1, group="1 - Inputs")
        exitAdx      = input.float({_pine_number(params.get("exit_adx", 20.0), force_float=True)}, "Exit ADX", step=0.1, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        emaFast = ta.ema(close, fastEmaLen)
        emaSlow = ta.ema(close, slowEmaLen)
        [diPlus, diMinus, adxVal] = ta.dmi(adxLen, adxLen)

        entrySignal = emaFast > emaSlow
        belowTrend  = close < emaSlow
        trendWeak   = (not na(adxVal) and not na(diPlus) and not na(diMinus)) ? (adxVal < exitAdx or diMinus > diPlus) : belowTrend
        exitCond    = strategy.position_size > 0 and belowTrend and trendWeak

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, "Bear Confirmed", yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(emaFast, "EMA Fast", color=color.new(color.orange, 0))
        plot(emaSlow, "EMA Slow", color=color.new(color.blue, 40))
        """,
    )


def _build_donchian_turtle(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Donchian Turtle",
        "Turtle",
        "donchian_turtle",
        f"""
        entryLen     = input.int({_pine_number(params.get("entry_len", 55))}, "Entry Channel Length", minval=1, group="1 - Inputs")
        exitLen      = input.int({_pine_number(params.get("exit_len", 20))}, "Exit Channel Length", minval=1, group="1 - Inputs")
        trendLen     = input.int({_pine_number(params.get("trend_len", 100))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        donUpper = ta.highest(high, entryLen)
        donLower = ta.lowest(low, exitLen)
        trendEma = ta.ema(close, trendLen)

        entrySignal = close >= donUpper and (na(trendEma) or close > trendEma)
        exitCond    = strategy.position_size > 0 and close <= donLower

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, "Donchian Breakdown", yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(donUpper, "Entry Channel", color=color.new(color.green, 50))
        plot(donLower, "Exit Channel", color=color.new(color.red, 50))
        """,
    )


def _build_slope_persistence(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Slope Persistence",
        "Slope",
        "slope_persistence",
        f"""
        emaLen        = input.int({_pine_number(params.get("ema_len", 50))}, "EMA Length", minval=1, group="1 - Inputs")
        slopeWindow   = input.int({_pine_number(params.get("slope_window", 5))}, "Slope Window", minval=1, group="1 - Inputs")
        entryBars     = input.int({_pine_number(params.get("entry_bars", 3))}, "Positive Slope Bars", minval=1, group="1 - Inputs")
        exitBars      = input.int({_pine_number(params.get("exit_bars", 5))}, "Negative Slope Bars", minval=1, group="1 - Inputs")
        atrPeriod     = input.int({_pine_number(params.get("atr_period", 30))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier = input.float({_pine_number(params.get("atr_mult", 3.5), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        cooldownBars  = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        emaVal = ta.ema(close, emaLen)
        atrVal = ta.atr(atrPeriod)
        slope  = emaVal - emaVal[slopeWindow]

        var int posCount = 0
        var int negCount = 0
        if not na(slope)
            if slope > 0
                posCount += 1
                negCount := 0
            else
                negCount += 1
                posCount := 0

        entrySignal = posCount >= entryBars
        isSlopeExit = strategy.position_size > 0 and negCount >= exitBars
        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        exitCond    = isSlopeExit or isAtrExit

        var string exitReason = na
        if strategy.position_size > 0
            if isSlopeExit
                exitReason := "Slope Reversal"
            else if isAtrExit
                exitReason := "ATR Shock"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            if isAtrExit
                negCount := 0
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(emaVal, "EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_trough_bounce(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Trough Bounce",
        "Trough",
        "trough_bounce",
        f"""
        rsiLen        = input.int({_pine_number(params.get("rsi_len", 9))}, "RSI Length", minval=1, group="1 - Inputs")
        lowLookback   = input.int({_pine_number(params.get("low_lookback", 40))}, "Low Lookback", minval=1, group="1 - Inputs")
        fastEmaLen    = input.int({_pine_number(params.get("fast_ema", 10))}, "Fast EMA Length", minval=1, group="1 - Inputs")
        slowEmaLen    = input.int({_pine_number(params.get("slow_ema", 50))}, "Slow EMA Length", minval=1, group="1 - Inputs")
        bouncePct     = input.float({_pine_number(params.get("bounce_pct", 15.0), force_float=True)}, "Bounce Percent", step=0.5, group="1 - Inputs")
        exitConfirm   = input.int({_pine_number(params.get("exit_confirm", 3))}, "Exit Confirmation Bars", minval=1, group="1 - Inputs")
        atrPeriod     = input.int({_pine_number(params.get("atr_period", 20))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier = input.float({_pine_number(params.get("atr_mult", 4.0), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        cooldownBars  = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        rsiVal    = ta.rsi(close, rsiLen)
        recentLow = ta.lowest(low, lowLookback)
        emaFast   = ta.ema(close, fastEmaLen)
        emaSlow   = ta.ema(close, slowEmaLen)
        atrVal    = ta.atr(atrPeriod)

        bounce    = recentLow > 0 ? (close / recentLow - 1) * 100 : na
        entryA    = not na(bounce) and bounce >= bouncePct and rsiVal > 30 and rsiVal[1] <= 30
        entryB    = ta.crossover(emaFast, emaSlow)
        entrySignal = entryA or entryB

        var int belowCount = 0
        if not na(emaFast) and not na(emaSlow)
            if emaFast < emaSlow
                belowCount += 1
            else
                belowCount := 0

        isCrossExit = strategy.position_size > 0 and belowCount >= exitConfirm
        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        exitCond    = isCrossExit or isAtrExit

        var string exitReason = na
        if strategy.position_size > 0
            if isCrossExit
                exitReason := "Confirmed Cross"
            else if isAtrExit
                exitReason := "ATR Shock"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            belowCount := 0
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(emaFast, "EMA Fast", color=color.new(color.orange, 0))
        plot(emaSlow, "EMA Slow", color=color.new(color.blue, 40))
        """,
    )


def _build_momentum_stayer(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Momentum Stayer",
        "Stayer",
        "momentum_stayer",
        f"""
        fastEmaLen    = input.int({_pine_number(params.get("fast_ema", 15))}, "Fast EMA Length", minval=1, group="1 - Inputs")
        slowEmaLen    = input.int({_pine_number(params.get("slow_ema", 50))}, "Slow EMA Length", minval=1, group="1 - Inputs")
        rsiLen        = input.int({_pine_number(params.get("rsi_len", 14))}, "RSI Length", minval=1, group="1 - Inputs")
        exitRsi       = input.float({_pine_number(params.get("exit_rsi", 30.0), force_float=True)}, "Exit RSI", step=0.1, group="1 - Inputs")
        volShortLen   = input.int({_pine_number(params.get("vol_short", 15))}, "Vol Short Length", minval=2, group="1 - Inputs")
        volLongLen    = input.int({_pine_number(params.get("vol_long", 60))}, "Vol Long Length", minval=2, group="1 - Inputs")
        volExitRatio  = input.float({_pine_number(params.get("vol_exit_ratio", 1.5), force_float=True)}, "Vol Exit Ratio", step=0.05, group="1 - Inputs")
        rocPeriod     = input.int({_pine_number(params.get("roc_period", 40))}, "ROC Period", minval=1, group="1 - Inputs")
        cooldownBars  = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        emaFast     = ta.ema(close, fastEmaLen)
        emaSlow     = ta.ema(close, slowEmaLen)
        rsiVal      = ta.rsi(close, rsiLen)
        dailyReturn = close[1] != 0 ? (close - close[1]) / close[1] : 0.0
        volShort    = ta.stdev(dailyReturn, volShortLen)
        volLong     = ta.stdev(dailyReturn, volLongLen)
        rocVal      = ta.roc(close, rocPeriod)

        entrySignal = emaFast > emaSlow and not na(rocVal) and rocVal > 0

        bearishSignals = 0
        bearishSignals += emaFast < emaSlow ? 1 : 0
        bearishSignals += (not na(rsiVal) and rsiVal < exitRsi) ? 1 : 0
        bearishSignals += (not na(volShort) and not na(volLong) and volLong > 0 and volShort / volLong > volExitRatio) ? 1 : 0

        exitCond = strategy.position_size > 0 and bearishSignals >= 2

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, "Multi Confirm Exit", yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(emaFast, "EMA Fast", color=color.new(color.orange, 0))
        plot(emaSlow, "EMA Slow", color=color.new(color.blue, 40))
        """,
    )


def _build_keltner_squeeze(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Keltner Squeeze",
        "Squeeze",
        "keltner_squeeze",
        f"""
        bbLen        = input.int({_pine_number(params.get("bb_len", 20))}, "BB Length", minval=1, group="1 - Inputs")
        bbMult       = input.float({_pine_number(params.get("bb_mult", 2.0), force_float=True)}, "BB Multiplier", step=0.1, group="1 - Inputs")
        keltLen      = input.int({_pine_number(params.get("kelt_len", 20))}, "Keltner Length", minval=1, group="1 - Inputs")
        keltMult     = input.float({_pine_number(params.get("kelt_mult", 1.5), force_float=True)}, "Keltner Multiplier", step=0.1, group="1 - Inputs")
        trendLen     = input.int({_pine_number(params.get("trend_len", 100))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        momLen       = input.int({_pine_number(params.get("mom_len", 12))}, "Momentum Length", minval=1, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        bbBasis   = ta.sma(close, bbLen)
        bbDev     = ta.stdev(close, bbLen) * bbMult
        bbUpper   = bbBasis + bbDev
        bbLower   = bbBasis - bbDev
        keltBasis = ta.ema(close, keltLen)
        keltAtr   = ta.atr(keltLen)
        keltUpper = keltBasis + keltAtr * keltMult
        keltLower = keltBasis - keltAtr * keltMult
        trendEma  = ta.ema(close, trendLen)
        momVal    = ta.mom(close, momLen)

        squeezeNow  = bbLower > keltLower and bbUpper < keltUpper
        squeezePrev = squeezeNow[1]
        trendOk     = na(trendEma) or close > trendEma
        entrySignal = squeezePrev and not squeezeNow and momVal > 0 and trendOk

        isMomExit    = strategy.position_size > 0 and momVal[1] > 0 and momVal <= 0
        isResqueeze  = strategy.position_size > 0 and not squeezePrev and squeezeNow
        exitCond     = isMomExit or isResqueeze

        var string exitReason = na
        if strategy.position_size > 0
            if isMomExit
                exitReason := "Mom Reversal"
            else if isResqueeze
                exitReason := "Re Squeeze"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(keltBasis, "Keltner Basis", color=color.new(color.blue, 40))
        """,
    )


def _build_vix_mean_revert(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - VIX Mean Revert",
        "VIX MR",
        "vix_mean_revert",
        f"""
        vixLookback  = input.int({_pine_number(params.get("vix_lookback", 252))}, "VIX Percentile Lookback", minval=2, group="1 - Inputs")
        vixEmaLen    = input.int({_pine_number(params.get("vix_ema_len", 10))}, "VIX EMA Length", minval=1, group="1 - Inputs")
        entryPctl    = input.float({_pine_number(params.get("entry_pctl", 85.0), force_float=True)}, "VIX Entry Percentile", step=1.0, group="1 - Inputs")
        exitPctl     = input.float({_pine_number(params.get("exit_pctl", 40.0), force_float=True)}, "VIX Exit Percentile", step=1.0, group="1 - Inputs")
        trendLen     = input.int({_pine_number(params.get("trend_len", 100))}, "Trend EMA Length", minval=1, group="1 - Inputs")
        trendBuffer  = input.float({_pine_number(params.get("trend_buffer", 5.0), force_float=True)}, "Trend Buffer Pct", step=0.1, group="1 - Inputs")
        panicVix     = input.float({_pine_number(params.get("panic_vix", 45.0), force_float=True)}, "Panic VIX", step=0.5, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        vixClose = request.security("CBOE:VIX", timeframe.period, close)
        vixPctl  = ta.percentrank(vixClose, vixLookback)
        vixSmooth = ta.ema(vixClose, vixEmaLen)
        trendEma = ta.ema(close, trendLen)

        vixWasHigh  = vixPctl >= entryPctl or vixPctl[1] >= entryPctl
        vixDeclines = vixSmooth < vixSmooth[1]
        trendOk     = na(trendEma) or close > trendEma * (1 - trendBuffer / 100)
        entrySignal = vixWasHigh and vixDeclines and trendOk

        isNormalizeExit = strategy.position_size > 0 and vixPctl <= exitPctl
        isPanicExit     = strategy.position_size > 0 and vixClose > panicVix
        exitCond        = isNormalizeExit or isPanicExit

        var string exitReason = na
        if strategy.position_size > 0
            if isNormalizeExit
                exitReason := "VIX Normalized"
            else if isPanicExit
                exitReason := "Panic VIX"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(trendEma, "Trend EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_vix_trend_regime(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - VIX Trend Regime",
        "VIX Trend",
        "vix_trend_regime",
        f"""
        shortEmaLen   = input.int({_pine_number(params.get("short_ema", 20))}, "Short EMA Length", minval=1, group="1 - Inputs")
        longEmaLen    = input.int({_pine_number(params.get("long_ema", 50))}, "Long EMA Length", minval=1, group="1 - Inputs")
        vixSlowLen    = input.int({_pine_number(params.get("vix_slow_len", 60))}, "VIX SMA Length", minval=1, group="1 - Inputs")
        vixEntryRatio = input.float({_pine_number(params.get("vix_entry_ratio", 0.9), force_float=True)}, "VIX Entry Ratio", step=0.01, group="1 - Inputs")
        vixExitRatio  = input.float({_pine_number(params.get("vix_exit_ratio", 1.3), force_float=True)}, "VIX Exit Ratio", step=0.01, group="1 - Inputs")
        atrPeriod     = input.int({_pine_number(params.get("atr_period", 30))}, "ATR Period", minval=1, group="1 - Inputs")
        atrMultiplier = input.float({_pine_number(params.get("atr_mult", 3.0), force_float=True)}, "ATR Multiplier", step=0.1, group="1 - Inputs")
        cooldownBars  = input.int({_pine_number(params.get("cooldown", 0))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        vixClose = request.security("CBOE:VIX", timeframe.period, close)
        vixSlow  = ta.sma(vixClose, vixSlowLen)
        emaShort = ta.ema(close, shortEmaLen)
        emaLong  = ta.ema(close, longEmaLen)
        atrVal   = ta.atr(atrPeriod)

        vixRatio    = vixSlow > 0 ? vixClose / vixSlow : na
        entrySignal = emaShort > emaLong and vixRatio < vixEntryRatio

        isVixExit   = strategy.position_size > 0 and vixRatio > vixExitRatio
        isTrendExit = strategy.position_size > 0 and ta.crossunder(emaShort, emaLong)
        isAtrExit   = strategy.position_size > 0 and close < close[1] - atrVal * atrMultiplier
        exitCond    = isVixExit or isTrendExit or isAtrExit

        var string exitReason = na
        if strategy.position_size > 0
            if isVixExit
                exitReason := "VIX Spike"
            else if isTrendExit
                exitReason := "EMA Cross"
            else if isAtrExit
                exitReason := "ATR Shock"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(emaShort, "EMA Short", color=color.new(color.orange, 0))
        plot(emaLong, "EMA Long", color=color.new(color.blue, 40))
        """,
    )


def _build_steady_trend(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - Steady Trend",
        "Steady",
        "steady_trend",
        f"""
        emaLen       = input.int({_pine_number(params.get("ema_len", 50))}, "EMA Length", minval=1, group="1 - Inputs")
        slopeWindow  = input.int({_pine_number(params.get("slope_window", 5))}, "Slope Window", minval=1, group="1 - Inputs")
        entryBars    = input.int({_pine_number(params.get("entry_bars", 3))}, "Entry Confirm Bars", minval=1, group="1 - Inputs")
        exitBars     = input.int({_pine_number(params.get("exit_bars", 5))}, "Exit Confirm Bars", minval=1, group="1 - Inputs")

        emaVal = ta.ema(close, emaLen)
        slope  = emaVal - emaVal[slopeWindow]

        var int posCount = 0
        var int negCount = 0
        if not na(slope)
            if slope > 0
                posCount += 1
                negCount := 0
            else
                negCount += 1
                posCount := 0

        entrySignal = posCount >= entryBars and close > emaVal
        exitCond    = strategy.position_size > 0 and negCount >= exitBars

        if exitCond
            strategy.close("Long")
            label.new(bar_index, high, "Slope Rev", yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        if strategy.position_size == 0 and entrySignal and not exitCond
            strategy.entry("Long", strategy.long)

        plot(emaVal, "EMA", color=color.new(color.blue, 40))
        """,
    )


def _build_rsi_recovery(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - RSI Recovery",
        "RSIRec",
        "rsi_recovery",
        f"""
        rsiLen    = input.int({_pine_number(params.get("rsi_len", 14))}, "RSI Length", minval=1, group="1 - Inputs")
        trendLen  = input.int({_pine_number(params.get("trend_len", 100))}, "Trend EMA", minval=1, group="1 - Inputs")
        entryRsi  = input.float({_pine_number(params.get("entry_rsi", 35), force_float=True)}, "Entry RSI", group="1 - Inputs")
        panicRsi  = input.float({_pine_number(params.get("panic_rsi", 20), force_float=True)}, "Panic RSI", group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 10))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        rsiVal   = ta.rsi(close, rsiLen)
        trendEma = ta.ema(close, trendLen)

        var bool wasOversold = false
        if rsiVal < entryRsi
            wasOversold := true

        entrySignal = wasOversold and rsiVal > entryRsi and close > trendEma
        if entrySignal
            wasOversold := false

        isPanic    = strategy.position_size > 0 and rsiVal < panicRsi
        isTrendBrk = strategy.position_size > 0 and close < trendEma and rsiVal < 45
        exitCond   = isPanic or isTrendBrk

        var string exitReason = na
        if strategy.position_size > 0
            if isPanic
                exitReason := "Panic"
            else if isTrendBrk
                exitReason := "Trend Break"

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, exitReason, yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(trendEma, "Trend EMA", color=color.new(color.blue, 40))
        hline(entryRsi, "Entry RSI", color=color.gray, linestyle=hline.style_dotted)
        hline(panicRsi, "Panic RSI", color=color.red, linestyle=hline.style_dotted)
        """,
    )


def _build_ema_regime(params: dict) -> str:
    return _wrap(
        "Project Montauk Candidate - EMA Regime",
        "EMAReg",
        "ema_regime",
        f"""
        fastLen      = input.int({_pine_number(params.get("fast_ema", 20))}, "Fast EMA", minval=1, group="1 - Inputs")
        slowLen      = input.int({_pine_number(params.get("slow_ema", 60))}, "Slow EMA", minval=1, group="1 - Inputs")
        entryConfirm = input.int({_pine_number(params.get("entry_confirm", 3))}, "Entry Confirm Bars", minval=1, group="1 - Inputs")
        exitConfirm  = input.int({_pine_number(params.get("exit_confirm", 5))}, "Exit Confirm Bars", minval=1, group="1 - Inputs")
        cooldownBars = input.int({_pine_number(params.get("cooldown", 5))}, "Cooldown Bars", minval=0, group="1 - Inputs")

        fastEma = ta.ema(close, fastLen)
        slowEma = ta.ema(close, slowLen)

        var int bullCount = 0
        var int bearCount = 0
        if not na(fastEma) and not na(slowEma)
            if fastEma > slowEma
                bullCount += 1
                bearCount := 0
            else
                bearCount += 1
                bullCount := 0

        entrySignal = bullCount == entryConfirm
        exitCond    = strategy.position_size > 0 and bearCount >= exitConfirm

        var int lastSellBar = na
        if exitCond
            strategy.close("Long")
            lastSellBar := bar_index
            label.new(bar_index, high, "Cross Conf", yloc=yloc.abovebar, style=label.style_label_down, color=color.red, textcolor=color.white, size=size.tiny)

        canEnter = strategy.position_size == 0 and (na(lastSellBar) or (bar_index - lastSellBar) > cooldownBars)
        if entrySignal and canEnter and not exitCond
            strategy.entry("Long", strategy.long)

        plot(fastEma, "Fast EMA", color=color.new(color.green, 40))
        plot(slowEma, "Slow EMA", color=color.new(color.red, 40))
        """,
    )


_BUILDERS = {
    "montauk_821": _build_montauk_821,
    "rsi_regime": _build_rsi_regime,
    "breakout": _build_breakout,
    "rsi_regime_trail": _build_rsi_regime_trail,
    "vol_regime": _build_vol_regime,
    "ichimoku_trend": _build_ichimoku_trend,
    "dual_momentum": _build_dual_momentum,
    "rsi_vol_regime": _build_rsi_vol_regime,
    "trough_bounce": _build_trough_bounce,
    "momentum_stayer": _build_momentum_stayer,
    "keltner_squeeze": _build_keltner_squeeze,
    "always_in_trend": _build_always_in_trend,
    "donchian_turtle": _build_donchian_turtle,
    "slope_persistence": _build_slope_persistence,
    "vix_mean_revert": _build_vix_mean_revert,
    "vix_trend_regime": _build_vix_trend_regime,
    "steady_trend": _build_steady_trend,
    "rsi_recovery": _build_rsi_recovery,
    "ema_regime": _build_ema_regime,
}


def supports_pine_strategy(strategy_name: str) -> bool:
    return strategy_name in _BUILDERS


def supported_pine_strategies() -> list[str]:
    return sorted(_BUILDERS)


def generate_pine_script(strategy_name: str, params: dict) -> str:
    builder = _BUILDERS.get(strategy_name)
    if not builder:
        raise ValueError(f"No Pine generator for strategy {strategy_name}")
    return builder(params)


def write_candidate_strategy(run_dir: str | Path, strategy_name: str, params: dict) -> str:
    run_path = Path(run_dir)
    run_path.mkdir(parents=True, exist_ok=True)
    text = generate_pine_script(strategy_name, params)
    output_path = run_path / "candidate_strategy.txt"
    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    return str(output_path)


def write_montauk_patch(run_dir: str | Path, strategy_name: str, params: dict) -> str | None:
    if strategy_name != "montauk_821":
        return None

    with open(ACTIVE_PINE_PATH, "r", encoding="utf-8", newline="") as f:
        pine_text = f.read()

    patched_text, _changes, _unmatched = patch_pine_script(pine_text, params)
    output_path = Path(run_dir) / "patched_strategy.txt"
    with open(output_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(patched_text)
    return str(output_path)
