#!/usr/bin/env bash
# Montauk 3.0 — host firewall.
#
# Default-deny inbound. SSH and RDP are reachable over the tailnet; RDP is
# reachable *nowhere else*, which is the second of the two independent controls
# protecting the graphical surface (the first is xrdp's own address binding in
# 40-desktop.sh).
#
# SAFETY: LAN SSH stays OPEN by default.
#
# This box is headless and in a basement. A firewall that admits only the
# tailnet is one Tailscale outage away from a trip downstairs with a borrowed
# monitor. So LAN SSH remains open until you have confirmed the tailnet path
# works and you explicitly close it:
#
#   sudo bash 20-firewall.sh                 # tailnet + LAN SSH  (default, safe)
#   sudo bash 20-firewall.sh --deny-lan-ssh  # tailnet only       (after verifying)
#
# Reverting is always possible from a physical console:
#
#   sudo nft flush ruleset && sudo systemctl restart ssh

set -euo pipefail
here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib.sh
. "$here/lib.sh"

need_root

DENY_LAN_SSH=0
[ "${1:-}" = "--deny-lan-ssh" ] && DENY_LAN_SSH=1

TS_IP=$(tailnet_ip)
if [ -z "$TS_IP" ]; then
  if [ "$DENY_LAN_SSH" -eq 1 ]; then
    die "refusing --deny-lan-ssh while Tailscale is down: that would lock you out"
  fi
  warn "Tailscale is not up; installing rules with LAN SSH open"
else
  ok "tailnet address: $TS_IP"
fi

step "Writing the ruleset"
{
  cat <<'EOF'
#!/usr/sbin/nft -f
# Montauk 3.0 appliance firewall — generated by 20-firewall.sh.
# Do not hand-edit; re-run the script instead.
#
# Tailscale maintains its own nftables table for routing and NAT. This is a
# separate table, so the two coexist: a packet must survive every table's
# filter chains, which is why tailscale0 is allowed explicitly below.

table inet montauk
delete table inet montauk

table inet montauk {
  chain input {
    type filter hook input priority filter; policy drop;

    iif lo accept comment "loopback"
    ct state established,related accept
    ct state invalid drop

    # ICMP: keep the network diagnosable. Rate-limited so it cannot be used
    # to load a two-core box.
    ip  protocol icmp   icmp  type { echo-request, destination-unreachable, time-exceeded } limit rate 10/second accept
    ip6 nexthdr icmpv6  icmpv6 type { echo-request, destination-unreachable, time-exceeded, packet-too-big, nd-neighbor-solicit, nd-neighbor-advert, nd-router-advert } limit rate 10/second accept

    # Tailscale's own transport. Without this the tailnet cannot establish a
    # direct path and falls back to a slower relay.
    udp dport 41641 accept comment "tailscale wireguard"

    # Everything on the tailnet: SSH for administration, RDP for the screen.
    iifname "tailscale0" tcp dport 22   accept comment "ssh over tailnet"
    iifname "tailscale0" tcp dport 3389 accept comment "rdp over tailnet (D83/D126)"
EOF

  if [ "$DENY_LAN_SSH" -eq 0 ]; then
    cat <<'EOF'

    # LAN SSH — the fallback that makes a Tailscale outage survivable without a
    # monitor. Close it with --deny-lan-ssh once the tailnet path is proven.
    tcp dport 22 accept comment "ssh over lan (fallback)"
EOF
  else
    cat <<'EOF'

    # LAN SSH is closed. The tailnet is the only administrative path.
    # Recovery from a physical console: nft flush ruleset
EOF
  fi

  cat <<'EOF'

    # RDP is never accepted off the tailnet. Stated as an explicit reject so a
    # misconfiguration shows up as a refused connection rather than a timeout.
    tcp dport 3389 reject with tcp reset comment "rdp is tailnet-only"

    counter comment "dropped by default policy"
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    ct state established,related accept
    iifname "tailscale0" accept
    oifname "tailscale0" accept
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
EOF
} >/etc/nftables.conf
chmod 0755 /etc/nftables.conf
ok "wrote /etc/nftables.conf"

step "Validating before applying"
# Check mode first. A syntax error caught here leaves the running ruleset
# untouched, which on a headless box is the difference between a typo and a
# trip downstairs with a monitor.
if ! nft -c -f /etc/nftables.conf; then
  die "ruleset is invalid; nothing applied, existing rules left alone"
fi
ok "ruleset parses"

step "Applying"
nft -f /etc/nftables.conf
systemctl enable --now nftables >/dev/null 2>&1
ok "ruleset active and enabled at boot"

step "Summary"
if [ "$DENY_LAN_SSH" -eq 1 ]; then
  warn "LAN SSH is CLOSED — the tailnet is now your only way in"
else
  ok "LAN SSH is open (fallback). Close it with --deny-lan-ssh once verified."
fi
ok "RDP: accepted on tailscale0, rejected everywhere else"

cat <<'NOTE'

  Before running --deny-lan-ssh, prove the tailnet path from your Mac:

    ssh <you>@<tailnet-ip> 'echo reachable'

  Only close the LAN door after that prints "reachable".

NOTE
