#!/usr/bin/env bash
# Montauk 3.0 — the graphical surface (D83, amended by D126).
#
# XFCE reached over RDP, bound to the tailnet interface only, installed but not
# enabled at boot. You start it from your Mac over SSH when you want a screen,
# and stop it when you are done.
#
# Per D126 this is a real screen you see and control, not an admin-only
# terminal: Montauk's own charts open here in a browser. What it is *not* is a
# component Montauk depends on. Every resident service runs headless and no
# signal, digest, or Gold decision waits on a desktop session existing.
#
# XFCE over GNOME/KDE because the box is a two-core i3-6100 whose capacity is
# committed elsewhere; RDP over VNC because it degrades better over a home
# uplink and does not need a display to already exist on a headless machine.
#
#   sudo bash 40-desktop.sh            # admin user detected from sudo
#   MONTAUK_ADMIN=max sudo -E bash 40-desktop.sh

set -euo pipefail
here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib.sh
. "$here/lib.sh"

need_root

ADMIN=${MONTAUK_ADMIN:-${SUDO_USER:-}}
[ -n "$ADMIN" ] || die "cannot determine your login; set MONTAUK_ADMIN=<user>"
id -u "$ADMIN" >/dev/null 2>&1 || die "no such user: $ADMIN"
ADMIN_HOME=$(getent passwd "$ADMIN" | cut -d: -f6)

TS_IP=$(require_tailnet_ip)
ok "tailnet address: $TS_IP"
ok "desktop session will run as: $ADMIN"

step "Installing XFCE and xrdp"
apt-get update -qq
# --no-install-recommends keeps this to a working desktop rather than a full
# Debian workstation. xfce4-goodies and friends are deliberately omitted.
apt_install \
  xfce4 \
  xfce4-terminal \
  dbus-x11 \
  xorgxrdp \
  xrdp \
  firefox-esr

step "Binding xrdp to the tailnet interface only"
# Two independent controls, because either alone is one mistake from exposure:
#   1. xrdp listens on the tailnet address and nowhere else (here)
#   2. nftables rejects 3389 on every other interface (20-firewall.sh)
if write_file /etc/xrdp/xrdp.ini 0644 <<EOF
; Montauk 3.0 appliance — generated by 40-desktop.sh
;
; address is pinned to this host's Tailscale IPv4. Reaching the desktop
; therefore requires already being on the tailnet, so RDP inherits Tailscale's
; device authorization instead of introducing a second, weaker front door.
;
; If the tailnet address ever changes, re-run this script.

[Globals]
ini_version=1
address=$TS_IP
port=3389
use_vsock=false
security_layer=negotiate
crypt_level=high
bitmap_compression=true
max_bpp=24
new_cursors=true
tcp_nodelay=true
tcp_keepalive=true

[Logging]
LogFile=/var/log/xrdp.log
LogLevel=INFO

[Xorg]
name=Montauk (XFCE)
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20
EOF
then
  systemctl daemon-reload
fi

step "Setting the session to XFCE for $ADMIN"
write_file "$ADMIN_HOME/.xsession" 0644 <<'EOF' || true
#!/bin/sh
# Montauk 3.0 appliance — XFCE session for RDP logins.
exec startxfce4
EOF
chown "$ADMIN":"$ADMIN" "$ADMIN_HOME/.xsession"

step "Disabling xrdp at boot (on-demand only)"
# D83: units installed, not enabled. An idle appliance has zero listening RDP
# sockets, which keeps both the attack surface and the two-core budget honest.
systemctl disable xrdp xrdp-sesman >/dev/null 2>&1 || true
systemctl stop    xrdp xrdp-sesman >/dev/null 2>&1 || true
ok "xrdp installed, disabled at boot, currently stopped"

step "Installing the screen on/off helpers"
write_file /usr/local/bin/montauk-screen 0755 <<'EOF' || true
#!/usr/bin/env bash
# Start or stop the appliance's graphical surface.
#
#   montauk-screen on      bring the desktop up
#   montauk-screen off     take it down
#   montauk-screen status  is it running, and where
set -euo pipefail
case "${1:-status}" in
  on)
    sudo systemctl start xrdp-sesman xrdp
    echo "desktop up on $(tailscale ip -4 | head -n1):3389"
    echo "connect with Microsoft's Windows App on macOS"
    ;;
  off)
    sudo systemctl stop xrdp xrdp-sesman
    echo "desktop down; zero RDP sockets listening"
    ;;
  status)
    if systemctl is-active --quiet xrdp; then
      echo "up on $(tailscale ip -4 | head -n1):3389"
    else
      echo "down"
    fi
    ;;
  *) echo "usage: montauk-screen {on|off|status}" >&2; exit 2 ;;
esac
EOF

cat <<NOTE

  The desktop is installed and off.

    From your Mac:  ssh $ADMIN@$TS_IP
    Then:           montauk-screen on
    Connect to:     $TS_IP:3389   (Microsoft Windows App, free on the Mac App Store)
    When done:      montauk-screen off

NOTE

ok "graphical surface complete"
